=== MTES-MCT/explorateur-ecocites/ecocite-application/ecocite-application/src/main/resources/cerbere/referentiel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Explorateur Écocités
  ~ Copyright (C) 2019 l'État, ministère chargé du logement
  ~
  ~ This program is free software: you can redistribute it and/or modify it under the terms of the Etalab Open License, version 2.0.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Etalab Open License for more details.
  ~
  ~ You should have received a copy of the Etalab Open License along with this program. If not, see <https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf>.
  -->

<xs:schema xmlns="http://cerbere.application.i2/schemas/CerbereBouchonSchema/2"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:cb="http://cerbere.application.i2/schemas/CerbereBouchonSchema/2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://cerbere.application.i2/schemas/CerbereBouchonSchema/2"
    elementFormDefault="qualified"
    xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">

    <xs:simpleType name="melType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\+\d+)? \d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sirenType">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="9"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="OuiNonType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="oui" />
            <xs:enumeration value="non" />
            <xs:enumeration value="0" />
            <xs:enumeration value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CiviliteType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M" />
            <xs:enumeration value="F" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="codePaysType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="adresseType">
        <xs:sequence>
            <xs:element name="rue" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="codepostal" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="ville" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="pays" type="codePaysType" minOccurs="0" maxOccurs="1" default="FR"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="utilisateurType">
        <xs:all>
            <xs:element name="civilite" type="CiviliteType" minOccurs="0" />
            <xs:element name="nom" type="xs:string" />
            <xs:element name="prenom" type="xs:string" />
            <xs:element name="identifiant" type="xs:string" />
            <xs:element name="passe" type="xs:string" />
            <xs:element name="matricule" type="xs:string" minOccurs="0" />
            <xs:element name="tel" type="telType" minOccurs="0" />
            <xs:element name="mobile" type="telType" minOccurs="0" />
            <xs:element name="fax" type="telType" minOccurs="0" />
            <xs:element name="adresse" type="adresseType" minOccurs="0" />
            <xs:element name="bureau" type="xs:string" minOccurs="0" />
        </xs:all>
        <xs:attribute name="mel" type="melType" use="required"/>
        <xs:attribute name="estActif" type="OuiNonType" default="1"/>
        <xs:attribute name="estVerifie" type="OuiNonType" default="1"/>
    </xs:complexType>

    <xs:complexType name="entiteType">
        <xs:sequence>
            <xs:element name="adresse" type="adresseType" minOccurs="0" maxOccurs="1" />
            <xs:element name="utilisateurs" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="utilisateur" type="utilisateurType" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="entite" type="entiteType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="nom" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:whiteSpace value="collapse"/>
                    <xs:minLength value="1"/>
                    <xs:pattern value="[^\\]*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="SIREN" type="sirenType"/>
        <xs:attribute name="estUnService" type="OuiNonType" default="0"/>
    </xs:complexType>

    <xs:complexType name="profilAppType">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="nom" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="applicationType" >
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="authentification" minOccurs="0" default="FORM">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="FORM" />
                        <xs:enumeration value="CERT" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="estSSO" type="OuiNonType" minOccurs="0" default="1"/>
            <xs:element name="profils-app">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="profil-app" type="profilAppType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="applicationId" type="xs:string" use="required" />
        <xs:attribute name="api" type="xs:integer" default="2" />
    </xs:complexType>

    <xs:complexType name="habilitationType">
        <xs:sequence>
            <xs:element name="profil" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="portee" type="xs:string" minOccurs="0" default="" />
                        <xs:element name="restriction" type="xs:string" minOccurs="0" default="" />
                    </xs:sequence>
                    <xs:attribute name="nom" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="mel" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="annuaire">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entites">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entite" type="entiteType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="racine" type="xs:string" default="" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="applications">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="application" type="applicationType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="habilitations" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="habilitation" type="habilitationType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="applicationId" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!-- clÃ©s d'unicitÃ©s -->
        <xs:key name="PK_MEL">
            <xs:selector xpath=".//cb:utilisateur"/>
            <xs:field xpath="@mel"/>
        </xs:key>
        <xs:unique name="PK_MATRICULE">
            <xs:selector xpath=".//cb:utilisateur"/>
            <xs:field xpath="cb:matricule"/>
        </xs:unique>
        <xs:unique name="PK_SIREN">
            <xs:selector xpath=".//cb:entite"/>
            <xs:field xpath="cb:siren"/>
        </xs:unique>
        <xs:unique name="PK_LOGIN">
            <xs:selector xpath=".//cb:utilisateur"/>
            <xs:field xpath="cb:identifiant"/>
        </xs:unique>
        <xs:key name="PK_APP">
            <xs:selector xpath=".//cb:application"/>
            <xs:field xpath="@applicationId"/>
        </xs:key>
        <!-- rÃ©fÃ©rences vers les clÃ©s -->
        <xs:keyref name="FK_HABILITATION_MEL" refer="PK_MEL">
            <xs:selector xpath=".//cb:habilitation" />
            <xs:field xpath="@mel" />
        </xs:keyref>
        <xs:keyref name="FK_HABILITATIONS_APP" refer="PK_APP">
            <xs:selector xpath=".//cb:habilitations" />
            <xs:field xpath="@applicationId" />
        </xs:keyref>
    </xs:element>
</xs:schema>

=== MTES-MCT/explorateur-ecocites/ecocite-application/src/main/resources/cerbere/cerbere-filtre-bouchon-dev.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Explorateur Écocités
  ~ Copyright (C) 2019 l'État, ministère chargé du logement
  ~
  ~ This program is free software: you can redistribute it and/or modify it under the terms of the Etalab Open License, version 2.0.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Etalab Open License for more details.
  ~
  ~ You should have received a copy of the Etalab Open License along with this program. If not, see <https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf>.
  -->

<annuaire xmlns="http://cerbere.application.i2/schemas/CerbereBouchonSchema/2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://cerbere.application.i2/schemas/CerbereBouchonSchema/2 referentiel.xsd">
    <entites racine="fr">
        <entite nom="equipement">
            <entite nom="AC">
                <entite nom="SG" estUnService="1">
                    <entite nom="A">
                        <entite nom="A3">
                            <utilisateurs>
                                <utilisateur mel="admin@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>M</civilite>
                                    <nom>Dmin</nom>
                                    <prenom>Adam</prenom>
                                    <identifiant>admin</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000001</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                    <bureau>B01</bureau>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                        <entite nom="A1">
                            <utilisateurs>
                                <utilisateur mel="admintech@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>M</civilite>
                                    <nom>Admin</nom>
                                    <prenom>Tech</prenom>
                                    <identifiant>admin_tech</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000010</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                    <bureau>B01</bureau>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                        <entite nom="A2">
                            <utilisateurs>
                                <utilisateur mel="accompagnateur@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>F</civilite>
                                    <nom>Compagnateur</nom>
                                    <prenom>Alice</prenom>
                                    <identifiant>accompagnateur</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000002</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                    </entite>
                    <entite nom="B">
                        <entite nom="B1">
                            <utilisateurs>
                                <utilisateur mel="action@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>M</civilite>
                                    <nom>Tion</nom>
                                    <prenom>Alain-Charles</prenom>
                                    <identifiant>action</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000003</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                    </entite>
                </entite>
            </entite>
            <entite nom="DR">
                <entite nom="DREAL Alsace" estUnService="1">
                    <entite nom="A">
                        <entite nom="A1">
                            <utilisateurs>
                                <utilisateur mel="ecocite@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>M</civilite>
                                    <nom>Cocite</nom>
                                    <prenom>Elise</prenom>
                                    <identifiant>ecocite</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000004</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                    </entite>
                </entite>
                <entite nom="DREAL Aquitaine" estUnService="1">
                    <entite nom="A">
                        <entite nom="A1">
                            <utilisateurs>
                                <utilisateur mel="acteur@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>F</civilite>
                                    <nom>Cteur</nom>
                                    <prenom>Arya</prenom>
                                    <identifiant>acteur</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>EQUTRH000000008</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                    </entite>
                </entite>
                <entite nom="DREAL Bretagne" estUnService="1">
                    <entite nom="A">
                        <entite nom="A1">
                            <utilisateurs>
                                <utilisateur mel="vide@explorateur.ecocites.logement.gouv.fr">
                                    <civilite>F</civilite>
                                    <nom>Géfroid</nom>
                                    <prenom>Sandra</prenom>
                                    <identifiant>sansdroit</identifiant>
                                    <passe>bouchon</passe>
                                    <matricule>JGAGJAGO73543</matricule>
                                    <tel>+33 111111111</tel>
                                    <mobile>+33 666666666</mobile>
                                    <fax>+33 122222222</fax>
                                </utilisateur>
                            </utilisateurs>
                        </entite>
                    </entite>
                </entite>
            </entite>
        </entite>
    </entites>

    <!-- L I S T E  D E S  A P P L I C A T I O N S  E T  D E  L E U R S
        P R O F I L S -->
    <applications>
        <application applicationId="615">
            <profils-app>
                <profil-app nom="administrateur"/>
                <profil-app nom="admin_tech"/>
                <profil-app nom="accompagnateur"/>
                <profil-app nom="acteur_ecocite_autre"/>
                <profil-app nom="referent_ecocite"/>
                <profil-app nom="porteur_action"/>
            </profils-app>
        </application>
    </applications>

    <!-- L I S T E  D E S  D R O I T S  S U R  L'A P P L I C A T I O N
        Les droits sont affectÃ©s par utilisateur. Chaque utilisateur est
        identifiÃ© de faÃ§on unique par son mel et contient plusieurs profils.
        Un profil est caractÃ©risÃ© par :
        - son profil d'application associÃ© [**obligatoire**]
        - une portÃ©e de service [facultatif]
        - une restriction libre [facultatif]
    -->
    <habilitations applicationId="615">
        <habilitation mel="admin@explorateur.ecocites.logement.gouv.fr">
            <profil nom="administrateur" />
        </habilitation>
        <habilitation mel="admintech@explorateur.ecocites.logement.gouv.fr">
            <profil nom="admin_tech" />
        </habilitation>
        <habilitation mel="accompagnateur@explorateur.ecocites.logement.gouv.fr">
            <profil nom="accompagnateur">
            </profil>
        </habilitation>
        <habilitation mel="action@explorateur.ecocites.logement.gouv.fr">
            <profil nom="porteur_action">
                <restriction>A_25768_67156, A_25768_67157</restriction>
            </profil>
            <profil nom="PORTEUR_ACTION">
                <restriction>A_25450</restriction>
            </profil>
        </habilitation>
        <habilitation mel="ecocite@explorateur.ecocites.logement.gouv.fr">
